#!name = Tachimanga Premium
#!desc = 破解 Tachimanga Premium 會員
#!author = Minis
#!homepage = https://github.com/r666bc/minis-qx

[Script]
Tachimanga = type=http-response,pattern=^https:\/\/api3\.tachimanga\.app\/api\/info\/fetch,script-path=https://raw.githubusercontent.com/r666bc/minis-qx/main/Scripts/JS/tachimanga_premium.js,requires-body=1,timeout=10

[MITM]
hostname = %APPEND% api3.tachimanga.app
