#!name = 火影忍者社區會員解鎖
#!desc = naruto-fe 火影忍者社區微信小程式 VIP 解鎖，偽造用戶 vip 狀態及 vip_member 標籤
#!author = Minis
#!homepage = https://github.com/r666bc/minis-qx

^https?://env-00jxgsbzdqch\.api-hz\.cloudbasefunction\.cn/functions/invokeFunction url script-response-body https://raw.githubusercontent.com/r666bc/minis-qx/main/Scripts/JS/naruto-fe-vip.js

hostname = env-00jxgsbzdqch.api-hz.cloudbasefunction.cn
