#!name = Tachimanga Premium 破解
#!desc = 偽造 info/fetch Premium 購買狀態，解鎖 Tachimanga 會員功能
#!author = Minis
#!homepage = https://github.com/r666bc/minis-qx

^https:\/\/api3\.tachimanga\.app\/api\/info\/fetch url script-response-body https://raw.githubusercontent.com/r666bc/minis-qx/main/Scripts/JS/tachimanga_premium.js

hostname = api3.tachimanga.app, *.tachimanga.app
